#!/usr/bin/env python3
"""Generate a syzbot-style kernel bug report from a local bug directory.

Structure follows syzbot's house style (provenance block, reproducer, crash,
Reported-by request) because maintainers are used to reading it. It is NOT a
syzbot report and never claims to be: the report is sent from your own address,
carries your own tracking id, and omits every syzbot/syzkaller marker.

Usage:
    mkbugreport.py <bug-dir> [--kdir DIR] [--send] [--id-len N]

Reads from <bug-dir>:
    report.md     title + root cause (first '# ' line is the title)
    decoded.txt   symbolized crash (falls back to qemu_output.log)
    exp.c         C reproducer (inlined)
    config        kernel .config (referenced; attach it yourself)

Prints the report and the matching git send-email command. Nothing is sent
unless --send is given.
"""

import argparse
import json
import textwrap
import os
import shlex
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import cfsend            # REST transport; port 465 is filtered on some nets

FROM_NAME = "co"
# Header From must live on the domain onboarded for Cloudflare Email Sending,
# or the submission is refused and DMARC fails at vger. Authorship of a patch
# is carried by the in-body "From:" line instead, which git send-email keeps.
FROM_ADDR = "co@bugs.sh"
REPORT_DOMAIN = "bugs.sh"
REPORT_LOCAL = "co"
ASSISTED_BY = "Claude:claude-opus-4-8"
# Reproduction rate is a measurement, not a default. Left empty the row is
# omitted entirely, so the tool never asserts a rate nobody counted. Set it
# per bug (--reproduces) once you have actually observed one.
REPRO_NOTE = ""

# Sanitizer labels read badly after a "subsys: driver:" prefix. Map them to
# the phrasing maintainers use in commit messages.
CLASS_NAMES = [
    (r"null-ptr-deref|kernel NULL pointer dereference", "NULL deref"),
    (r"slab-use-after-free|use-after-free",             "use-after-free"),
    (r"slab-out-of-bounds|global-out-of-bounds"
     r"|stack-out-of-bounds|out-of-bounds",             "out-of-bounds access"),
    (r"invalid-free|double-free",                       "invalid free"),
    (r"wild-memory-access",                             "wild memory access"),
    (r"general protection fault",                       "GPF"),
    (r"soft lockup",                                    "soft lockup"),
    (r"data-race",                                      "data race"),
    (r"WARNING",                                        "WARNING"),
]

# Provenance, not analysis: every claim here is one we verified by running
# it. Nothing a model asserted about the bug appears in the mail body.
METHOD = ("Found by LLM-assisted source analysis, not fuzzing. The finding "
          "was then reproduced on a real build -- the sanitizer report and "
          "reproducer above are from an actual boot, not from a model.")

# Where the LLM-generated material lives. Kept out of the mail body: a
# maintainer should be able to read the verifiable parts -- config, the
# sanitizer report,
# reproducer -- without wading through a model's analysis first.
FEEDBACK_CONTACT = "cedalion@bugs.sh"

# Carried as the reproducer's first line rather than an Environment row:
# it belongs next to the code it builds.
COMPILE_CMD = "gcc -O2 -static -o repro repro.c"

REPO_URL = "https://github.com/n132/cedalion"
# Lives beside the register it reads: bugs.json for the bug id and the
# lore link, artifacts.json for what has been disclosed.
CEDALION = Path(__file__).resolve().parent
BUGS_JSON = CEDALION / "bugs.json"
SITE = "https://bugs.sh"

# The report links to bugs.sh/b/<id>/<file> and never to a storage location,
# and never conditionally: a mailed report is immutable, so the URL it carries
# has to be the one whose meaning we still control after the files move -- and
# after they are disclosed. It reads artifacts.json for nothing, because what
# is disclosed on the day of sending is not what the link has to be right for.


def known_bug(bug_id):
    """Is this id in the corpus? A miss means the wrong directory."""
    try:
        data = json.loads(BUGS_JSON.read_text())
    except (OSError, ValueError):
        return True          # cannot check; do not block on it
    return any(b.get("bug_id") == bug_id for b in data.get("bugs", []))

FOOTER = f"""---
The report format is based on syzbot bug report.

This report is generated by a bot. It may contain errors.
See {REPO_URL} for more information.

For any issue with this report, reach out to {FEEDBACK_CONTACT}

If the report is already addressed, let us know by replying with:
#co fix: <commit hash>

If the report is a duplicate of another one, reply with:
#co dup: <lore link>

If you want to undo deduplication, reply with:
#co undup"""

# The distinction the Notes section exists to draw: what is demonstrated
# versus what is a model's output awaiting review.
NOTE_PROVED = "Everything in this mail is validated by the reproducer below."

NOTE_PROJECT = ("This is an open science project. The code and the full set "
                "of PoCs are not public at this moment, as we intend to "
                "disclose our findings in an ethical way.")

NOTE_LLM = ("We also hold an LLM-generated root-cause analysis and a candidate "
            "patch. The patch passes an A/B test: the same reproducer panics "
            "the unpatched kernel and runs clean on the patched one. Neither "
            "has had human review, so both still require validation before "
            "you send or apply them. Available on:")

# Cloudflare Email Sending: implicit TLS on 465, user is the literal string
# "api_token", password is the API token (read from $CF_API_TOKEN at send time
# so it never lands in a config file).
SMTP = {
    "smtp-server": "smtp.mx.cloudflare.net",
    "smtp-server-port": "465",
    "smtp-encryption": "ssl",
    "smtp-user": "api_token",
}

# Lines that carry no diagnostic value in a mailed report.
NOISE = re.compile(
    r"^\s*("
    r"\?|<TASK>|</TASK>|Code:|Modules linked in:|"
    r"R[A-D]X:|R[SB]P:|RSI:|RDI:|R[89]:|R1[0-5]:|"
    r"FS:|CS:|CR2:|PKRU:|PGD |#PF:|Tainted:|Hardware name:|"
    r"---\[ end trace"
    r")"
)

# decode_stacktrace.sh expands `Code:` into disassembly blocks. syzbot never
# carries these and they dwarf the trace, so drop from the header to the blank
# line / next non-indented section.
DISASM_START = re.compile(r"^(All code|Code starting with the faulting)")
DISASM_LINE = re.compile(
    r"^(=+\s*$|\s*\.\.\.\s*$"
    r"|\s*[0-9a-f]+:[\s*]"          # '  1a:', '  2a:*' — hex offsets
    r"|\s+[0-9a-f]{2}(\s[0-9a-f]{2})*\s*$)"   # continuation byte rows
)


def sh(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return r.stdout.strip()


def read(p):
    return p.read_text(errors="replace") if p.exists() else ""


WIDTH = 72          # leaves room for one level of quoting inside 80 cols


def sec(title, ch="="):
    """A section rule that survives any mail client: pure ASCII, fixed width.

        == Summary ====================================================
    """
    head = f"{ch * 2} {title} "
    return head + ch * max(3, WIDTH - len(head))


def wrap(text, n=4):
    """Reflow prose to WIDTH, indented n spaces. Mutt does not reflow for you."""
    pad = " " * n
    return "\n".join(
        textwrap.fill(para.strip(), width=WIDTH,
                      initial_indent=pad, subsequent_indent=pad)
        for para in re.split(r"\n\s*\n", text.strip()) if para.strip())


def rows(pairs, n=4, gap=2):
    """Aligned key/value rows.

    Column width follows the longest key so a label can be renamed without
    silently colliding with its value. Values are never wrapped: they are
    meant to be copy-pasted.
    """
    pairs = [(k, v) for k, v in pairs if v]
    if not pairs:
        return ""
    w = max(len(k) for k, _ in pairs) + gap
    return "\n".join(f"{' ' * n}{k:<{w}}{v}" for k, v in pairs)


TIMESTAMP = re.compile(r"^\[\s*\d+\.\d+\]\s?")
DISCRIM = re.compile(r"\s*\(discriminator \d+\)")
LOC_CHAIN = re.compile(r"\(([^()]*?:\d+[^()]*)\)")


def slim_trace(crash):
    """Keep one source location per frame.

    decode_stacktrace.sh prints the entire inline chain, which pushes a
    single frame past 250 columns and makes the trace unreadable in an
    80-column terminal. The innermost location is the useful one.
    """
    def keep_last(m):
        return "(" + m.group(1).split()[-1] + ")"

    out = []
    for l in crash.splitlines():
        l = LOC_CHAIN.sub(keep_last, DISCRIM.sub("", l))
        out.append(l)
    return "\n".join(out)


def strip_c_comments(src):
    """Remove C comments without touching string or char literals.

    A regex cannot do this safely -- "http://x" and '/' would both be
    mangled -- so this walks the source in four states.
    """
    out, i, n, state = [], 0, len(src), "code"
    while i < n:
        c, nxt = src[i], src[i + 1] if i + 1 < n else ""
        if state == "code":
            if c == "/" and nxt == "*":
                state, i = "block", i + 2
                continue
            if c == "/" and nxt == "/":
                state, i = "line", i + 2
                continue
            if c == '"':
                state = "str"
            elif c == "'":
                state = "chr"
            out.append(c)
            i += 1
        elif state in ("str", "chr"):
            if c == "\\":                       # escape: copy the pair whole
                out.append(src[i:i + 2])
                i += 2
                continue
            if (state == "str" and c == '"') or (state == "chr" and c == "'"):
                state = "code"
            out.append(c)
            i += 1
        elif state == "block":
            if c == "*" and nxt == "/":
                state, i = "code", i + 2
                continue
            if c == "\n":                        # keep line numbering intact
                out.append("\n")
            i += 1
        else:                                    # line comment
            if c == "\n":
                state = "code"
                out.append("\n")
            i += 1

    text = "\n".join(l.rstrip() for l in "".join(out).splitlines())
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def indent(text, n=4):
    """Indent a block so it sits under its section heading."""
    pad = " " * n
    return "\n".join(pad + l if l.strip() else l for l in text.splitlines())


def summary_of(bugdir):
    """First paragraph under '## Root cause' in report.md.

    This is the part a fuzzer cannot produce, so it leads the report.
    """
    text = read(bugdir / "report.md")
    m = re.search(r"^##+\s*Root cause\s*$(.+?)(?=^##|\Z)", text,
                  re.M | re.S)
    if not m:
        return title_of(bugdir)
    para = m.group(1).strip().split("\n\n")[0]
    return " ".join(l.strip() for l in para.splitlines() if l.strip())


def impact_of(bugdir):
    """Who can trigger this, from report.md's reachability section.

    A maintainer's third question after "is this mine": does it matter.
    An unprivileged-reachable panic is triaged differently from one that
    needs root.
    """
    text = read(bugdir / "report.md")
    m = re.search(r"^##+\s*(?:Reachability|Impact)[^\n]*$(.+?)(?=^##|\Z)",
                  text, re.M | re.S)
    if not m:
        return ""
    para = m.group(1).strip().split("\n\n")[0]
    text = " ".join(l.strip() for l in para.splitlines() if l.strip())
    keep = [sent for sent in re.split(r"(?<=\.)\s+", text)
            if not re.search(r"\bCVE\b", sent)]
    return " ".join(keep).strip()


def title_of(bugdir):
    """First markdown H1 in report.md, minus any leading bug number."""
    for line in read(bugdir / "report.md").splitlines():
        if line.startswith("# "):
            return re.sub(r"^\d+\s*[-—]\s*", "", line[2:].strip())
    return bugdir.name


# Anything that opens a crash report, and the subset that means the machine
# actually died. A WARNING is in the first and not the second: kernels warn
# during a healthy boot, and none of those is the bug being reported.
CRASH_ANY = re.compile(
    r"(BUG:|Oops:|WARNING:|general protection fault|KASAN:|UBSAN:|KCSAN:)")
CRASH_HARD = re.compile(
    r"(KASAN:|KCSAN:|UBSAN:|Oops:|general protection fault"
    r"|BUG: unable to handle|BUG: kernel NULL|BUG: soft lockup|BUG: sleeping)")

# A symbolized frame: decode_stacktrace.sh rewrites `func+0x12/0x34` into
# `func (path/file.c:123)`. Nothing else in a console log looks like that.
SYMBOLIZED = re.compile(r"\([^()]*\.[ch]:\d+")

# How far apart two crash markers can be and still be one crash. A KASAN
# report runs about 100 lines from its header to the Oops that follows it,
# with the allocation and free stacks in between; an unrelated warning from
# earlier in the boot is thousands of lines away. 200 separates the two
# comfortably without joining two real crashes that happened back to back.
CRASH_GAP = 200


def crash_block(bugdir, trim=False):
    """The crash log.

    Verbatim by default -- a log a maintainer cannot trust to be complete is
    worth less than a long one. `trim` drops register dumps, disassembly and
    repeated dumps for readability, and is opt-in for that reason.
    """
    for name in ("decoded.txt", "qemu_output.log"):
        text = read(bugdir / name)
        if not text:
            continue
        # Falling back is not a detail. decoded.txt is the symbolized trace;
        # qemu_output.log is the raw console, whose frames carry no file:line
        # at all. A report built from the second one looks finished and is
        # worth much less, so say which one this is.
        if name != "decoded.txt":
            print(f"warning: no decoded.txt in {bugdir} -- building the crash "
                  f"from {name}, whose trace is not symbolized", file=sys.stderr)
        lines = text.splitlines()

        # The crash that ended the run, not the first thing in the log that
        # looked like one. A boot carries warnings of its own -- an "Invalid
        # wait context" from timekeeping_init, a firmware complaint -- and
        # taking the first match reports one of those instead of the bug,
        # symbolized and formatted and completely wrong. So: prefer a hard
        # crash over a warning, prefer the last one, and ignore anything after
        # the panic, which is teardown.
        panic = next((i for i, l in enumerate(lines) if "Kernel panic" in l), None)
        found = [i for i, l in enumerate(lines) if CRASH_ANY.search(l)
                 and (panic is None or i <= panic)]
        strong = [i for i in found if CRASH_HARD.search(lines[i])]
        marks = strong or found
        if not marks:
            continue
        # One crash prints several of these. A KASAN null deref opens with
        # "BUG: KASAN: ..." and goes on to "BUG: kernel NULL pointer
        # dereference" and "Oops:" a hundred lines later, all one event -- so
        # the last marker is the middle of the report, and starting there drops
        # the line that says what the bug actually is. Walk back through
        # markers that are close enough to belong to the same crash; a boot
        # warning hundreds of lines earlier is not one of them.
        start = marks[-1]
        for i in range(len(marks) - 1, 0, -1):
            if marks[i] - marks[i - 1] > CRASH_GAP:
                break
            start = marks[i - 1]

        if not trim:
            last = max((i for i, l in enumerate(lines) if "Kernel panic" in l),
                       default=len(lines) - 1)
            # Drop the console timestamp prefix only: it is noise, and it
            # costs ~15 columns on every line. Nothing else is touched.
            return checked("\n".join(TIMESTAMP.sub("", l)
                                     for l in lines[start:last + 1]), bugdir)

        end = next(
            (i for i, l in enumerate(lines[start + 1:], start + 1)
             if re.match(r"^\[?\s*\d*\.?\d*\]?\s*={20,}", l)),
            min(start + 90, len(lines) - 1),
        )
        panic = next((l for l in lines if "Kernel panic" in l), None)
        out, in_disasm = [], False
        for l in lines[start:end]:
            l = re.sub(r"^\[\s*\d+\.\d+\]\s*", "", l).rstrip()
            if DISASM_START.match(l):
                in_disasm = True
                continue
            if in_disasm:
                if DISASM_LINE.match(l) or not l.strip():
                    continue
                in_disasm = False
            if NOISE.match(l) or not l.strip():
                continue
            out.append(l)
        if panic:
            out.append(re.sub(r"^\[\s*\d+\.\d+\]\s*", "", panic).rstrip())
        return checked("\n".join(out), bugdir)
    return "(no crash log found)"


def checked(block, bugdir):
    """The crash block, having said so if it is not symbolized.

    The whole value of the Sanitizer Report to a maintainer is that every frame
    names a file and a line. An unsymbolized block is the same crash with that
    thrown away, and it is not visible in the output that anything is missing --
    it just reads as a shorter trace. So this is the last thing between a broken
    input and a mailed report that looks right.
    """
    if block and not SYMBOLIZED.search(block):
        print(f"warning: the crash in {bugdir} has no symbolized frames -- "
              f"decode it (scripts/decode_stacktrace.sh against this build's "
              f"vmlinux) into decoded.txt before sending", file=sys.stderr)
    return block


def crash_signature(crash):
    """Class + faulting symbol, e.g. ('KASAN: null-ptr-deref', '_raw_spin_lock')."""
    m = re.search(
        r"(KASAN: [a-z-]+|BUG: [A-Za-z ]+?|WARNING|general protection fault)"
        r"(?: in | at )([A-Za-z_][A-Za-z0-9_]*)",
        crash,
    )
    raw, func = (m.group(1).strip(), m.group(2)) if m else (
        (crash.splitlines()[0] if crash else "crash")[:60], "")
    for pattern, name in CLASS_NAMES:
        if re.search(pattern, raw, re.I):
            return name, func
    return raw, func


def source_files(bugdir):
    """Kernel source paths the report implicates, in order of appearance."""
    return re.findall(r"\b((?:drivers|net|fs|kernel|mm|sound)/\S+?\.[ch])\b",
                      read(bugdir / "report.md"))


# Path segments that carry no routing information for a maintainer.
NOISE_SEG = {"drivers", "ethernet", "net" if False else ""}


def subsystem(bugdir, kdir):
    """Subsystem prefix in the form maintainers use on patches.

    drivers/net/ethernet/qualcomm/rmnet/x.c  ->  net: qualcomm: rmnet
    net/sched/sch_taprio.c                   ->  net: sched
    fs/ext4/inode.c                          ->  fs: ext4

    This is what a maintainer filters on. A bare filename tells them
    nothing about whether the mail is theirs.
    """
    files = source_files(bugdir)
    if not files:
        return "kernel"
    segs = [x for x in files[0].split("/")[:-1]
            if x not in ("drivers", "ethernet")]
    return ": ".join(segs[:3]) or "kernel"


# Frames that are plumbing, never the subject of a report.
GENERIC = re.compile(r"^(kernel|lib|mm)/|^\./|^arch/")


def faulting_func(crash, bugdir):
    """The frame worth naming: the first one inside the implicated subsystem.

    The innermost frame is usually _raw_spin_lock or a KASAN helper, which
    says nothing about which bug this is.
    """
    files = source_files(bugdir)
    scope = "/".join(files[0].split("/")[:-1]) + "/" if files else None
    # tolerate the console timestamp prefix on verbatim logs
    frames = re.findall(
        r"^(?:\[\s*\d+\.\d+\])?\s*([a-zA-Z_][\w.]*)\s+\(([^)]+)\)",
        crash, re.M)
    if scope:
        for name, loc in frames:
            if loc.strip().startswith(scope):
                return name.split(".")[0]
    for name, loc in frames:
        if not GENERIC.match(loc.strip()):
            return name.split(".")[0]
    return ""


def config_symbols(bugdir):
    """Non-default CONFIG symbols the report says are needed to reach the bug.

    Worth more to a maintainer than the attached .config: 'cannot reproduce'
    is nearly always a missing symbol, and nobody greps a 135K file for it.
    """
    prose = read(bugdir / "report.md")
    config = read(bugdir / "config")

    # Candidates: explicit CONFIG_FOO, plus bare FOO_BAR tokens (reports
    # routinely write "enabling NET_VENDOR_QUALCOMM" without the prefix).
    cand = {m.lstrip("CONFIG_") if m.startswith("CONFIG_") else m
            for m in re.findall(r"\b(?:CONFIG_)?([A-Z][A-Z0-9_]{2,})\b", prose)}

    # Confirm against the config actually used, so guesses cannot leak into
    # a report a maintainer will try to follow.
    enabled = set(re.findall(r"^CONFIG_([A-Z0-9_]+)=[ym]", config, re.M))
    return sorted(f"CONFIG_{c}" for c in cand & enabled)


def vm_setup(bugdir):
    """The qemu cmdline — this is what stands in for syzbot's disk image."""
    m = re.search(r'-append\s+"([^"]+)"', read(bugdir / "run.sh"))
    return m.group(1) if m else ""


def maintainers(bugdir, kdir):
    """get_maintainer.pl over the file(s) the report implicates."""
    files = sorted(set(re.findall(r"\b((?:drivers|net|fs|kernel|mm)/\S+?\.[ch])\b",
                                  read(bugdir / "report.md"))))
    if not files or not (kdir / "scripts/get_maintainer.pl").exists():
        return [], []
    out = sh(["perl", "scripts/get_maintainer.pl", "--nogit", "--nogit-fallback",
              "-f", *files], cwd=kdir)
    to, cc = [], []
    for line in out.splitlines():
        addr = line.split(" (")[0].strip()
        if not addr:
            continue
        (cc if "list" in line else to).append(addr)
    return to, cc


def build(bugdir, kdir, slim=False, trim=False,
          keep_comments=False, with_analysis=False, repro_note=REPRO_NOTE):
    crash = crash_block(bugdir, trim)
    trace = slim_trace(crash) if slim else crash
    klass, func = crash_signature(crash)
    subsys = subsystem(bugdir, kdir)
    func = faulting_func(crash, bugdir) or func
    head = sh(["git", "log", "-1", "--format=%h %s"], cwd=kdir) or "unknown"
    head_hash = head.split()[0]
    # Standard kernel citation form: hash ("subject"), as in Fixes: tags.
    head_ref = f'{head_hash} ("{head.split(" ", 1)[-1]}")'

    # The bug id is cedalion's, not ours: the directory name is the primary
    # key in bugs.json, so a reply or a Reported-by tag joins straight back
    # to the corpus. Deriving our own would have produced an id that exists
    # nowhere else and changes whenever the crash signature is reworded.
    bug_id = bugdir.resolve().name
    if not known_bug(bug_id):
        print(f"warning: {bug_id} is not in {BUGS_JSON}", file=sys.stderr)
    report_addr = f"{REPORT_LOCAL}+{bug_id}@{REPORT_DOMAIN}"

    what = f"{klass} in {func}()" if func else klass
    subject = f"[BUG] {subsys}: {what}"
    repro = read(bugdir / "exp.c")
    if not keep_comments:
        repro = strip_c_comments(repro)
    repro = f"// {COMPILE_CMD}\n{repro}"
    cfg = "config.gz" if (bugdir / "config").exists() else "not available"
    syms = config_symbols(bugdir)
    cmdline = vm_setup(bugdir)
    summary = summary_of(bugdir)
    impact = impact_of(bugdir)

    # Everything syzbot hosts (vmlinux, bzImage, disk image) is omitted: a
    # maintainer rebuilds from commit + config. What cannot be omitted is the
    # config delta, the VM setup and the privilege context.
    required = ((",\n" + " " * 16).join(syms) if syms
                else "(nothing beyond defconfig identified)")

    # Every row is the URL, disclosed or not. This mail is archived on lore the
    # day it is sent and never edited again, so the link has to be the one that
    # will be right later: /b/<id>/<file> says "not public yet" now and serves
    # the file once it is cleared, and the reader who kept the mail follows the
    # same link to get it.
    env = rows([
        ("Reproduced on", head_ref),
        ("VM setup", f"{SITE}/b/{bug_id}/run.sh"),
        ("config", f"{SITE}/b/{bug_id}/config.gz"),
        ("poc", f"{SITE}/b/{bug_id}/repro.c"),
    ])

    # What NOTE_LLM's "Available on:" points at: the patch and the analysis it
    # just described, one URL each, whatever is disclosed today.
    #
    # This mail lands in the LKML archive and stays there, so the link has to
    # outlive the state it was written in. A URL does: /b/<id>/report.md answers
    # "not public yet" now and serves the file the day it is cleared, and the
    # reader who saved the mail follows the same link to get it. The word
    # "pending" would be frozen at the moment of sending and never become true.
    llm_where = rows([(name, f"{SITE}/b/{bug_id}/{name}")
                      for name in ("patch.diff", "report.md")], n=8)

    # The "net: qualcomm: rmnet" form is for the subject line; here a
    # maintainer wants the path. Broken out as a block rather than a
    # sentence so path, crash and commit are all findable at a glance.
    files = source_files(bugdir)
    scope = "/".join(files[0].split("/")[:-1]) if files else subsys
    lead = "\n".join([
        "We found a bug reachable in:",
        "",
        rows([("path", scope),
              ("crash", f"{klass} in {func}()" if func else klass),
              ("commit", head_ref)]),
        "",
        "Config, environment, the sanitizer report and a C reproducer follow.",
    ])

    analysis = ""
    if with_analysis:
        analysis = (f"{sec('Analysis (LLM-generated, unverified)')}\n"
                    f"{wrap(summary)}\n\n"
                    + (f"{wrap(impact)}\n\n" if impact else ""))

    body = f"""{lead}

{sec("Notes")}
    If you patch the bug based on our artifacts, a tag would be
    appreciated:

Reported-by: {report_addr}

{wrap(NOTE_PROVED)}

{wrap(NOTE_LLM)}

{llm_where}

{wrap(NOTE_PROJECT)}

    Happy to test patches. Complaints and suggestions about our work
    are welcome at:

        {FEEDBACK_CONTACT}

{sec("Environment")}
{env}

{sec("Sanitizer Report")}
{trace}

{analysis}
{FOOTER}
"""
    to, cc = maintainers(bugdir, kdir)
    return subject, body, to, cc, report_addr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bugdir", type=Path)
    ap.add_argument("--kdir", type=Path, default=Path.home() / "net")
    ap.add_argument("--reproduces", default=REPRO_NOTE, metavar="RATE",
                    help='observed reproduction rate, e.g. "every boot" or\n"3 of 10 boots". Omitted from the report unless given.')
    ap.add_argument("--with-analysis", action="store_true",
                    help="append the LLM root-cause analysis at the end.\nOff by default; the mail carries verifiable material only.")
    ap.add_argument("--keep-comments", action="store_true",
                    help="keep comments in the inlined reproducer.\nThey are stripped by default.")
    ap.add_argument("--trim-report", action="store_true",
                    help="drop register dumps, disassembly and repeated\ndumps. Off by default: the log goes out complete.")
    ap.add_argument("--slim-report", action="store_true",
                    help="collapse decode_stacktrace inline chains to the\ninnermost location. Off by default: log output goes out verbatim.")
    ap.add_argument("--send", action="store_true",
                    help="actually send, over the Cloudflare REST API")
    ap.add_argument("--maintainers", action="store_true",
                    help="send to the get_maintainer.pl list. Deliberate\nflag: without it --send only goes where --to says.")
    ap.add_argument("--dry-run", action="store_true",
                    help="hand off to git send-email --dry-run")
    ap.add_argument("--to", action="append", metavar="ADDR",
                    help="override recipients entirely (repeatable). Use this\nfor test sends -- without it --send mails the real maintainer list.")
    args = ap.parse_args()

    subject, body, to, cc, addr = build(args.bugdir, args.kdir, args.slim_report,
                                  args.trim_report, args.keep_comments,
                                  args.with_analysis, args.reproduces)
    out = args.bugdir / "bugreport.eml"
    # From carries the tag, so a reply threads to this bug without a separate
    # Reply-To and without asking anyone to keep a tag they did not choose.
    out.write_text(f"Subject: {subject}\n"
                   f"From: {FROM_NAME} <{addr}>\n\n{body}")

    print(f"=== {out} ===\nSubject: {subject}\nReported-by: {addr}\n")
    print(body[:1500] + ("\n... [truncated]\n" if len(body) > 1500 else ""))

    # --confirm=never: this runs unattended; recipients are already explicit.
    print(f"=== {out} ===")
    print(f"Subject: {subject}")
    print(f"Reported-by: {addr}")
    print(f"{len(body.splitlines())} lines, {len(body)/1024:.1f} KiB\n")

    if args.maintainers:
        recipients = to + cc
    elif args.to:
        recipients = args.to
    else:
        recipients = []

    if not args.send:
        print("Recipients if --maintainers were given:")
        for a in to + cc:
            print(f"  {a}")
        print("\nNot sent. Add --send with --to ADDR (test) or --maintainers (real).")
        return

    if not recipients:
        sys.exit("--send needs --to ADDR or --maintainers")

    print("Sending to:")
    for a in recipients:
        print(f"  {a}")
    payload = cfsend.build(out.read_text(), to_override=recipients)
    result = cfsend.send(payload)
    print("sent" if result.get("success") else f"FAILED: {result.get('errors')}")


if __name__ == "__main__":
    main()
